version: "3.9"

services:
  app:
    build: .
    ports:
      - "3333:3000"
    environment:
      NODE_ENV: production
      PORT: 3333
    volumes:
      - projects_data:/app/.local
    restart: unless-stopped

volumes:
  projects_data:
    driver: local
